In [58]:
import requests
from bs4 import BeautifulSoup as BTS
import pandas as pd

In [28]:
ticker = '005930'

In [29]:
url = f'https://finance.naver.com/item/sise.naver?code={ticker}'

In [30]:
headers = {
    'user-agent': 'Mozilla/5.0'
}

In [31]:
res = requests.get(url=url, headers=headers)

In [32]:
res.status_code

200

In [33]:
res.text

'<!--  global include -->\n\n\t\n\t\n<html lang=\'ko\'>\n<head>\n\n\n\t\n\t\t<title>삼성전자 : Npay 증권</title>\n\t\n\t\n\n\n\n\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n\n<meta http-equiv="Content-Script-Type" content="text/javascript">\n<meta http-equiv="Content-Style-Type" content="text/css">\n<meta name="apple-mobile-web-app-title" content="Npay 증권" />\n\n\n\n\n\n\t\n\t\t<meta property="og:title" content="Npay 증권"/>\n\t\t<meta property="og:image" content="https://ssl.pstatic.net/static/m/stock/im/2016/08/og_stock-200.png"/>\n\t\t<meta property="og:url" content="https://finance.naver.com"/>\n\t\t<meta property="og:description" content="국내 해외 증시 지수, 시장지표, 뉴스, 증권사 리서치 등 제공"/>\n    \n    \n\n<meta property="og:type" content="article"/>\n<meta property="og:article:thumbnailUrl" content=""/>\n<meta property="og:article:author" content="Npay 증권"/>\n<meta property="og:article:author:url" content="http://FINANCE.NAVER.COM"/>\n\n\n\n\n\n\n<link rel=\'stylesheet\' type=\'text/css\' href=\'https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/finance_header.css\'>\n\n\t\n\t\n\t\n\t\n\t\t\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/newstock.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/common.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/layout.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/main.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/newstock2.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/newstock3.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/world.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/css/community.css">\n\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/js/jindo.min.ns.1.5.3.euckr.js"></script>\n\t\t\t\t<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/js/release/common.js"></script>\n\t\t\t\t<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/js/jindoComponent/jindo.Component.1.0.3.js"></script>\n\t\t\t\t<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20260304232456/js/nhn.autocomplete.stock.js"></script>\n\t\t\t\n\t\t\n\n\t\t\n\t\n\n<script>\n\tvar ieVersion = (function () {\n        var version = -1;\n        if (\n          navigator.appName == \'Microsoft Internet Explorer\' &&\n          navigator.userAgent.toLowerCase().indexOf(\'msie\') != -1 &&\n          new RegExp(\'MSIE ([0-9]{1,}[\\./0-9]{0,})\').exec(navigator.userAgent) != null\n        ) {\n          version = parseInt(RegExp.$1);\n        }\n        return version;\n      })();\n</script>\n\t\n\t<!-- smart channel 광고 -->\n\t<script async src="https://ssl.pstatic.net/tveta/libs/glad/prod/gfp-core.js">\n\t\t</script>\n\t<script type="text/javascript">\n\t\t(function(){\n\t\t\tif (ieVersion === -1 || ieVersion > 10) {\n\t\t\t\twindow.gladsdk = window.gladsdk || { cmd: [] };\n\n\t\t\t\tgladsdk.cmd.push(function() {\n\t\t\t\t\t\tgladsdk.defineAdSlot({\n\t\t\t\t\t\t\tadUnitId: "p_new_stock",\n\t\t\t\t\t\t\tadSlotElementId: "_SmartChannelTopBanner",\n\t\t\t\t\t\t\tuct: "KR",\n\t\t\t\t\t\t\tcustomParam: {\n\t\t\t\t\t\t\t\tcalp: \n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t"home"\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t});\n\n\t\t\t\t\t\tgladsdk.addEventListener(gladsdk.event.AD_LOADED, function(ad) {\n\t\t\t\t\t\t\t//console.log(gladsdk.event.AD_LOADED);\n\t\t\t\t\t\t});\n\t\t\t\t\t\tgladsdk.addEventListener(gladsdk.event.AD_CLICKED, function(ad) {\n\t\t\t\t\t\t\t//console.log(gladsdk.event.AD_CLICKED);\n\t\t\t\t\t\t});\n\t\t\t\t\t\tgladsdk.addEventListener(gladsdk.event.AD_IMPRESSED, function(ad) {\n\t\t\t\t\t\t\t//console.log(gladsdk.event.AD_IMPRESSED);\n\t\t\t\t\t\t});\n\t\t\t\t\t\tgladsdk.addEventListener(gladsdk.event.ERROR, function(ad, error) {\n\t\t\t\t\t\t\t//TODO: 오류 로깅처리\n\t\t\t\t\t\t\t//console.log(gladsdk.event.ERROR);\n\t\t\t\t\t\t});\n\t\t\t\t\t});\n\n\t\t\t\tgladsdk.cmd.push(function() {\n\t\t\t\t\tgladsdk.defineAdSlot({\n\t\t\t\t\t\tadUnitId: "p_new_stock_top_sidebox",\n\t\t\t\t\t\tadSlotElementId: "_SmartChannelTopBannerSidebox",\n\t\t\t\t\t\tuct: "KR",\n\t\t\t\t\t\tcustomParam: {\n\t\t\t\t\t\t\tcalp: \n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t"home"\n\t\t\t\t\t\t},\n\t\t\t\t\t});\n\n\t\t\t\t\tgladsdk.addEventListener(gladsdk.event.AD_LOADED, function(ad) {\n\t\t\t\t\t\t//console.log(gladsdk.event.AD_LOADED);\n\t\t\t\t\t});\n\t\t\t\t\tgladsdk.addEventListener(gladsdk.event.AD_CLICKED, function(ad) {\n\t\t\t\t\t\t//console.log(gladsdk.event.AD_CLICKED);\n\t\t\t\t\t});\n\t\t\t\t\tgladsdk.addEventListener(gladsdk.event.AD_IMPRESSED, function(ad) {\n\t\t\t\t\t\t//console.log(gladsdk.event.AD_IMPRESSED);\n\t\t\t\t\t});\n\t\t\t\t\tgladsdk.addEventListener(gladsdk.event.ERROR, function(ad, error) {\n\t\t\t\t\t\t//TODO: 오류 로깅처리\n\t\t\t\t\t\t//console.log(gladsdk.event.ERROR);\n\t\t\t\t\t});\n\t\t\t\t});\n\t\t\t}\n\t\t})();\n\t</script>\n\t\n\n\t<link rel="shortcut icon" href="https://ssl.pstatic.net/imgstock/favi/favicon.ico" type="image/x-icon">\n\t\n\t<script type="text/javascript">\n    (function(){\n\t\tdocument.write(\n\t\t\t\t[\n\t\t\t\t\t\'<link rel="apple-touch-icon-precomposed" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>\',\n\t\t\t\t\t\'<link rel="apple-touch-icon-precomposed" sizes="180x180" href="https://ssl.pstatic.net/imgstock/favi/favicon-180x180.png"/>\',\n\t\t\t\t\t\'<link rel="apple-touch-icon-precomposed" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>\',\n\t\t\t\t\t\'<link rel="icon" type="image/png" sizes="16x16" href="https://ssl.pstatic.net/imgstock/favi/favicon-16x16.png"/>\',\n\t\t\t\t\t\'<link rel="icon" type="image/png" sizes="32x32" href="https://ssl.pstatic.net/imgstock/favi/favicon-32x32.png"/>\',\n\t\t\t\t\t\'<link rel="icon" type="image/png" sizes="96x96" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>\',\n\t\t\t\t\t\'<link rel="icon" type="image/png" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>\'\n\t\t\t\t]\n\t\t\t.join(\'\\n\')\n\t\t);\n    })();\n    </script>\n</head>\n\n\n\n\n<body onload=\'getGNB();\'>\n\n\n\n\n<script type="text/javascript">\n\n\n\n\n\n\n\nvar nsc="finance.stockend";\n\n\nvar ccsrv="cc.naver.com";\n\n\n\t\n\t\n\tvar gnb_service=\'finance\';\n\t\n\n\nvar gnb_logout=document.URL; //GNB에서 로그아웃 후 redirect 될 URL\nvar gnb_searchbox=\'off\'; //미니 검색창을 on 할지 off 할지. default는 off\nvar gnb_shortnick=\'off\'; //닉네임 말줄임(10자)을 on할지 off 할지. default는 off.\n\n\nvar gnb_naverme_layer_open_callback = function(){\n\t   var naverLayerSize = gnbNaverMeLayer.getLayerSize();\n\t\t\n\t\tvar me_layers = document.getElementById("me_layers");\n\t\tme_layers.width=naverLayerSize.width;\n\t\tme_layers.height=naverLayerSize.height;};\n\nvar gnb_naverme_layer_close_callback = function(){\n\t\t\n\t\t\tvar me_layers = document.getElementById("me_layers");\n\t\t\tme_layers.width="0";\n\t\t\tme_layers.height="0";};\n</script>\n\n\n<div id="u_skip">\n\t<a href="#menu" tabindex="1"><span>메인 메뉴로 바로가기</span></a>\n\n\t\n\t\t<a href="#middle" tabindex="2"><span>본문으로 바로가기</span></a>\n\t\n\t\n\n</div>\n\n\n<div id="header">\n\t<div class="header_area">\n\t\t<div class="header_inner">\n\t\t\t<div class="logo_area">\n\t\t\t\t<h1 class="service">\n\t\t\t\t\t<a href="https://www.naver.com/" class="logo_link" onClick="clickcr(this, \'STA.naver\', \'\', \'\', event);">\n\t\t\t\t\t\t<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n\t\t\t\t\t\t\t<path d="M22 11C22 13.1756 21.3549 15.3023 20.1462 17.1113C18.9375 18.9202 17.2195 20.3301 15.2095 21.1627C13.1995 21.9952 10.9878 22.2131 8.85401 21.7886C6.72022 21.3642 4.76021 20.3166 3.22183 18.7782C1.68345 17.2398 0.635805 15.2798 0.211368 13.146C-0.213069 11.0122 0.00476298 8.80047 0.837327 6.79048C1.66989 4.78049 3.07979 3.06253 4.88873 1.85383C6.69768 0.645137 8.82441 0 11 0C13.9174 0 16.7153 1.15893 18.7782 3.22183C20.8411 5.28473 22 8.08262 22 11ZM12.8398 5.83V11.3602L8.98976 5.83H5.83V16.1838H9.1575V10.637L13.0075 16.17H16.1783V5.83H12.8398Z" fill="#000"/>\n\t\t\t\t\t\t</svg>\n\t\t\t\t\t\t<span class="blind">네이버</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<a href="https://new-m.pay.naver.com/" class="logo_link" onClick="clickcr(this, \'STA.pay\', \'\', \'\', event);">\n\t\t\t\t\t\t<svg width="37" height="22" viewBox="0 0 37 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n\t\t\t\t\t\t\t<path d="M34.4319 5.21944L31.3913 12.1478L27.9518 5.21944H25.3072L30.1783 14.8317L28.1703 19.3358H30.7384L37 5.2331L34.4319 5.21944ZM23.6171 15.9331H21.1037V14.9328C20.1894 15.7342 19.0108 16.1685 17.7953 16.1518C14.7901 16.1518 12.4379 13.692 12.4379 10.5763C12.4379 7.46057 14.7874 5.00079 17.7953 5.00079C19.0104 4.9833 20.189 5.41657 21.1037 6.21701V5.21944H23.6171V15.9331ZM21.3987 10.5899C21.3987 8.57019 19.9891 7.03694 18.1204 7.03694C16.2517 7.03694 14.842 8.57019 14.842 10.5899C14.842 12.6097 16.249 14.1429 18.1204 14.1429C19.9918 14.1429 21.3987 12.596 21.3987 10.5899ZM0.00819554 19.3358H2.63088V15.023C3.52823 15.7695 4.66309 16.1699 5.83001 16.1518C8.83516 16.1518 11.1901 13.692 11.1901 10.5763C11.1901 7.46057 8.83789 5.00079 5.83001 5.00079C4.61166 4.9789 3.42899 5.4126 2.51341 6.21701V5.21944H0L0.00819554 19.3358ZM5.51856 7.03694C7.38722 7.03694 8.79691 8.57019 8.79691 10.5899C8.79691 12.6097 7.38722 14.1429 5.51856 14.1429C3.6499 14.1429 2.24021 12.6097 2.24021 10.5899C2.24021 8.57019 3.63351 7.03694 5.51856 7.03694Z" fill="#000"/>\n\t\t\t\t\t\t</svg>\n\t\t\t\t\t\t<span class="blind">페이</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<a href="/" class="logo_link" onClick="clickcr(this, \'STA.finance\', \'\', \'\', event);">\n\t\t\t\t\t\t<svg width="34" height="22" viewBox="0 0 34 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n\t\t\t\t\t\t\t<path d="M2.43006 8.88998L1.85406 6.99998C5.29206 6.31598 7.00206 5.34398 7.45206 4.31798H2.71806V2.35598H14.3641V4.31798H9.75606C9.70206 4.65998 9.61206 4.98398 9.46806 5.28998L15.2101 6.98198L14.4901 8.88998L8.02806 6.92798C6.84006 7.75598 5.00406 8.40398 2.43006 8.88998ZM0.612061 11.5V9.53798H16.4521V11.5H0.612061ZM6.53406 12.796H10.5301C13.2301 12.796 14.7961 14.128 14.7961 15.91C14.7961 17.71 13.2301 19.024 10.5301 19.024H6.53406C3.85206 19.024 2.28606 17.71 2.28606 15.91C2.28606 14.128 3.85206 12.796 6.53406 12.796ZM6.96606 17.044H10.1161C11.7901 17.044 12.4921 16.594 12.4921 15.892C12.4921 15.19 11.7901 14.776 10.1161 14.776H6.96606C5.29206 14.776 4.57206 15.19 4.57206 15.892C4.57206 16.594 5.29206 17.044 6.96606 17.044Z" fill="#000"/>\n\t\t\t\t\t\t\t<path d="M25.1904 13.354V11.536H29.4564V2.03198H31.7604V15.334H29.4564V13.354H25.1904ZM21.3384 10.564C20.9244 10.582 20.5464 10.582 20.1684 10.582H17.4504L17.3604 8.61998H20.3844C21.5004 8.61998 22.9584 8.56598 24.4884 8.45798C24.7224 6.99998 24.8484 5.63198 24.8664 4.62398H18.4404V2.66198H27.0984V3.56198C27.0984 5.16398 26.9724 6.76598 26.7564 8.25998L28.2684 8.09798L28.5024 10.006C26.9724 10.222 25.2264 10.384 23.5704 10.474C23.4984 11.5 23.3904 12.562 23.2644 13.714L21.0684 13.588C21.1764 12.508 21.2664 11.536 21.3384 10.564ZM22.4724 14.254V16.756H32.3724V18.844H20.1684V14.254H22.4724Z" fill="#000"/>\n\t\t\t\t\t\t</svg>\n\t\t\t\t\t\t<span class="blind">증권</span>\n\t\t\t\t\t</a>\n\t\t\t\t</h1>\n\t\t\t</div>\n\n\t\t\t<div class="right_area">\n\t\t\t\t<div class="search_area">\n\t\t\t\t\t<form name="search" action="/search/search.naver"  method="get" onsubmit="return delayed_submit(this)" style="margin:0; padding:0;">\n\t\t\t\t\t<label for="stock_items" class="blind">증권 종목명·지수명 검색</label>\n\t\t\t\t\t<input type="text" id="stock_items" name="query" title="종목명·지수명 검색" class="search_input" placeholder="종목명&middot;지수명 입력" accesskey="s" autocomplete="off">\n\t\t\t\t\t<input type="hidden" id="_endUrl" name="endUrl" value="" />\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t<button type="submit" class="search_button" onclick="clickcr(this, \'STA.search\', \'\', \'\', event);">\n\t\t\t\t\t\t<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n\t\t\t\t\t\t\t<path fill-rule="evenodd" clip-rule="evenodd" d="M6.9999 2.59996C4.56985 2.59996 2.5999 4.56991 2.5999 6.99996C2.5999 9.43002 4.56985 11.4 6.9999 11.4C9.42996 11.4 11.3999 9.43002 11.3999 6.99996C11.3999 4.56991 9.42996 2.59996 6.9999 2.59996ZM1.3999 6.99996C1.3999 3.90717 3.90711 1.39996 6.9999 1.39996C10.0927 1.39996 12.5999 3.90717 12.5999 6.99996C12.5999 10.0928 10.0927 12.6 6.9999 12.6C3.90711 12.6 1.3999 10.0928 1.3999 6.99996Z" fill="#404048"></path>\n\t\t\t\t\t\t\t<path fill-rule="evenodd" clip-rule="evenodd" d="M10.2421 10.2424C10.4765 10.0081 10.8564 10.0081 11.0907 10.2424L14.424 13.5758C14.6583 13.8101 14.6583 14.19 14.424 14.4243C14.1897 14.6586 13.8098 14.6586 13.5755 14.4243L10.2421 11.091C10.0078 10.8567 10.0078 10.4768 10.2421 10.2424Z" fill="#404048"></path>\n\t\t\t\t\t\t</svg>\n\t\t\t\t\t\t<span class="blind">검색</span>\n\t\t\t\t\t</button>\n\t\t\t\t\t<div class="auto_area">\n\t\t\t\t\t\t<span class="blind">자동완성</span>\n\t\t\t\t\t\t<div id="autoFrame" style="display: none;">\n\t\t\t\t\t\t\t<div class="wrap" id="atcmp" style="display:none;">\n\t\t\t\t\t\t\t\t<div class="wrap_in">\n\t\t\t\t\t\t\t\t\t<div class="words">\n\t\t\t\t\t\t\t\t\t\t<ul class="_resultBox">\n\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t\t\t\t\t\t<a href="#" onclick="clickcr(this, \'AUT.list\', \'\', \'\', event); return false;" class="_au_real_list">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class="num _au_real_list">@code@</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class="_au_real_list">@txt@</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class="type _au_real_list">@market@</span>\n\t\t\t\t\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_full">@full_txt@</div>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_code">@in_code@</div>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_name">@in_name@</div>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_link">@in_link@</div>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_market">@in_market@</div>\n\t\t\t\t\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t</ul>\n\t\t\t\t\t\t\t\t\t\t<div class="search_notice">\n\t\t\t\t\t\t\t\t\t\t\t<p class="text">\n\t\t\t\t\t\t\t\t\t\t\t\t공모주와 해외 종목은 모바일 페이지로 이동합니다.\n\t\t\t\t\t\t\t\t\t\t\t</p>\n\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<!-- 현재 자동완성 기능을 사용하고 계십니다 -->\n\t\t\t\t\t\t\t\t<div class="wrap" id="atcmpIng" style="display:none;">\n\t\t\t\t\t\t\t\t\t<div class="wrap_in">\n\t\t\t\t\t\t\t\t\t\t<div class="words">\n\t\t\t\t\t\t\t\t\t\t\t<p class="msg">\n\t\t\t\t\t\t\t\t\t\t\t\t현재 자동완성 기능을 사용하고 계십니다.\n\t\t\t\t\t\t\t\t\t\t\t</p>\n\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<!--// 현재 자동완성 기능을 사용하고 계십니다 -->\n\t\t\t\t\t\t\t\t<!-- 자동완성 기능이 활성화 -->\n\t\t\t\t\t\t\t\t<div class="wrap" id="atcmpStart" style="display:none;">\n\t\t\t\t\t\t\t\t\t<div class="wrap_in">\n\t\t\t\t\t\t\t\t\t\t<div class="words">\n\t\t\t\t\t\t\t\t\t\t\t<p class="msg">\n\t\t\t\t\t\t\t\t\t\t\t\t자동완성 기능이 활성화되었습니다.\n\t\t\t\t\t\t\t\t\t\t\t</p>\n\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t\t</form>\n\t\t\t\t</div>\n\t\t\t\t<div class="gnb_area">\n\t\t\t\t\t<div id="gnb">\n\t\t\t\t\t\t<script charset="EUC-KR" type="text/javascript">\n\t\t\t\t\t\t\tvar gnb_service = "finance";\n\t\t\t\t\t\t\tvar gnb_template = location.protocol === "http:" ? "gnb_quirks_euckr" : "gnb_utf8" ;\n\t\t\t\t\t\t\tvar gnb_logout=encodeURIComponent(location.href);\n\t\t\t\t\t\t\tvar gnb_brightness = 1;\n\t\t\t\t\t\t\tvar gnb_one_naver = 0;\n\t\t\t\t\t\t</script>\n\t\t\t\t\t\t<script type="text/javascript" charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?20260324">\n\t\t\t\t\t\t</script>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\t<div class="lnb_area ">\n\t\t<div class="lnb_inner">\n\t\t\t<div id="menu">\n\t\t\t\t<ul class="menu">\n\t\t\t\t\t<li class="m1 first "><a href="/" onClick="clickcr(this, \'LNB.home\', \'\', \'\', event);"><span class="tx">증권 홈</span></a></li>\n\t\t\t\t\t<li class="m2 on"><a href="/sise/" onClick="clickcr(this, \'LNB.sise\', \'\', \'\', event);"><span class="tx">국내증시</span><span class="blind">선택됨</span></a></li>\n\t\t\t\t\t<li class="m3 "><a href="/world/" onClick="clickcr(this, \'LNB.world\', \'\', \'\', event);"><span class="tx">해외증시</span></a></li>\n\t\t\t\t\t<li class="m4 "><a href="/marketindex/" onClick="clickcr(this, \'LNB.market\', \'\', \'\', event);"><span class="tx">시장지표</span></a></li>\n\t\t\t\t\t<li class="m6 "><a href="/research/" onClick="clickcr(this, \'LNB.research\', \'\', \'\', event);"><span class="tx">리서치</span></a></li>\n\t\t\t\t\t<li class="m7 "><a href="/news/"><span class="tx">뉴스</span></a></li>\n\t\t\t\t\t<li class="m8 "><a href="/mystock/" onClick="clickcr(this, \'LNB.mystock\', \'\', \'\', event);"><span class="tx">MY</span></a></li>\n\t\t\t\t</ul>\n\t\t\t\t<!-- 새로운 증권보기 버튼 -->\n\t\t\t\t<div class="area_stock_button">\n\t\t\t\t\t<a href="https://stock.naver.com" class="link_new">\n\t\t\t\t\t\t<span class="icon_refresh"></span>\n\t\t\t\t\t\t새로운 증권 보기\n\t\t\t\t\t\t<span class="icon_new">\n\t\t\t\t\t\t\t<span class="blind">NEW</span>\n\t\t\t\t\t\t</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<span class="tooltip">\n\t\t\t\t\t\t더 편리해진 증권을 만나보세요\n\t\t\t\t\t\t<span class="icon_arrow"></span>\n\t\t\t\t\t</span>\n\t\t\t\t</div>\n\t\t\t\t<!-- //새로운 증권보기 버튼 -->\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\t\n\t\n\t\n\t\n\n\t\n\t<script type="text/JavaScript">\n\t\t/* lcs 집계 */\n        ;(function(){\n            var eventType = "onpageshow" in window ? "pageshow" : "load";\n            jindo.$Fn(function(){\n                lcs_do();\n            }).attach(window, eventType);\n        })();\n\n\t\t/* 검색 자동완성 [ 인자1 : 검색input의 ID, 인자2 : iframe 태그 ID ]   */\n\t\t// AutoComplete 생성\n\t\tvar acDomain = "ac.stock.naver.com";\n\t\tif (location.hostname.indexOf("staging-") > -1) {\n\t\t\tacDomain = "staging-" + acDomain;\n\t\t} else if (location.hostname.indexOf("test-") > -1) {\n\t\t\tacDomain = "test-" + acDomain;\n\t\t} else if (location.hostname.indexOf("dev-") > -1 || location.hostname.indexOf("localhost") > -1 || location.hostname.indexOf("local-") > -1) {\n\t\t\tacDomain = "dev-" + acDomain;\n\t\t}\n\n        var acUrl = "https://" + acDomain + "/ac";\n\n\t\tsmartSearch = new nhn.Autocomplete(\n\t\t\t// InputManager 생성\n\t\t\tnew nhn.AcInputManager(jindo.$("stock_items")),\n\t\t\t// DataManager 생성\n\t\t\tnew nhn.AcDataManager(acUrl, "xhr", "get", {}),\n\t\t\t// ViewManager 생성\n\t\t\tnew nhn.AcStockViewManager(jindo.$("autoFrame"), jindo.$("nautocomplete"), {\n                                        strMax: 200,\n                                        listMax: [7, 2, 2],\n                                        aRedirectUrl: [\n\t\t\t\t\t\t\t\t\t\t"https://" + window.location.hostname,\n                            \t\t\t"https://finance.naver.com",\n                            \t\t\t"https://finance.naver.com"],\n\t\t\t\t\t\t\t\t\t\tmobileUrl: "https://m.stock.naver.com"}),\n\t\t\t// Autocomplete Option\n      

In [34]:
res.headers['content-type']

'text/html;charset=EUC-KR'

In [36]:
soup = BTS(markup=res.text, features='html.parser')

- BeautifulSoup 객체는 select 메서드에 원하는 CSS Selector(선택자)를 지정하여 수집하려는 텍스트를 포함하고 있는 HTML elements를 빠르게 필터링할 수 있음

In [56]:
def get_price_daily(ticker, page=1):
    url = f'https://finance.naver.com/item/sise_day.naver'
    query = {'code': ticker, 'page': page}
    headers = {'user-agent': 'Mozilla/5.0'}

    res = requests.get(url=url, headers=headers, params=query)
    soup = BTS(markup=res.text, features='html.parser')

    items_1 = soup.select(selector='td.num:nth-child(2) > span.tah.p11')
    price = [item.text for item in items_1]

    items_2 = soup.select(selector='td[align="center"]:nth-child(1) > span.tah.p10')
    date = [item.text for item in items_2]

    df = pd.DataFrame(data={'date': date, 'price': price})

    return df

In [57]:
get_price_daily(ticker='005930')

         date    price
0  2026.03.24  189,700
1  2026.03.23  186,300
2  2026.03.20  199,400
3  2026.03.19  200,500
4  2026.03.18  208,500
5  2026.03.17  193,900
6  2026.03.16  188,700
7  2026.03.13  183,500
8  2026.03.12  187,900
9  2026.03.11  190,000

In [61]:
import time
from tqdm.notebook import tqdm

In [62]:
dfs = pd.DataFrame()
for page in tqdm(range(10)):
    page += 1
    df = get_price_daily(ticker = '005930', page = page)
    dfs = pd.concat(objs = [dfs, df], ignore_index = True)
    time.sleep(1)

  0%|          | 0/10 [00:00<?, ?it/s]

In [63]:
dfs

          date    price
0   2026.03.24  189,700
1   2026.03.23  186,300
2   2026.03.20  199,400
3   2026.03.19  200,500
4   2026.03.18  208,500
..         ...      ...
95  2025.10.31  107,500
96  2025.10.30  104,100
97  2025.10.29  100,500
98  2025.10.28   99,500
99  2025.10.27  102,000

[100 rows x 2 columns]