## Pandas Time Series 연습문제

이 노트북은 Pandas의 시계열 데이터를 사용하기 위한 연습문제로 구성되어 있습니다.

### 필요한 모듈 임포트

In [1]:
# 필요한 모듈을 임포트합니다.
import numpy as np
import pandas as pd

In [2]:
# pandas 버전을 확인합니다.
# [참고] 이 노트북은 pandas 2.3.2 버전에서 작성되었습니다.
pd.__version__

'2.3.3'

### 가상의 시계열 데이터 불러오기

In [3]:
# 가상의 시게열 데이터를 읽고 데이터프레임을 생성합니다.
df = pd.read_csv(filepath_or_buffer = 'https://bit.ly/Time_Series_Dataset')

In [4]:
# df의 처음 5행을 확인합니다.
df.head()

            date  sales
0  2026년 03월 02일  45.37
1  2026년 03월 23일  52.86
2  2026년 02월 15일  81.27
3  2026년 02월 27일  65.28
4  2026년 01월 09일  53.12

In [5]:
# df의 정보를 확인합니다.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    90 non-null     object
 1   sales   83 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.5+ KB

### 연습 문제 1: 날짜시간 데이터로 변환

In [6]:
# df에서 date를 날짜시간형으로 변환
df['date'] = pd.to_datetime(arg=df['date'], format='%Y년 %m월 %d일')

In [7]:
# df의 열별 자료형을 확인하세요.
# [참고] date의 원소 자료형은 'datetime64[ns]'이어야 합니다.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    90 non-null     datetime64[ns]
 1   sales   83 non-null     float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.5 KB

In [8]:
# df에서 date를 인덱스로 설정하고, 인덱스를 오름차순 정렬하여 df에 재할당하세요.
df = df.set_index(keys='date').sort_index()

In [9]:
# df의 처음 5행을 확인하세요.
df.head()

            sales
date
2026-01-01  48.12
2026-01-02  44.98
2026-01-03  77.56
2026-01-04  69.65
2026-01-05  40.89

### 연습 문제 2: 시계열 데이터의 인덱싱 및 슬라이싱

In [10]:
# df에서 인덱스가 '2026-02-02'인 행을 선택하세요.(인덱싱)
df.loc['2026-02-02', :]

sales    39.42
Name: 2026-02-02 00:00:00, dtype: float64

In [11]:
# df에서 인덱스가 '2026-03-01'부터 '2026-03-10'까지인 행을 잘라내세요.(슬라이싱)
df.loc['2026-03-01':'2026-03-10', :]

            sales
date
2026-03-01  92.02
2026-03-02  45.37
2026-03-03  50.22
2026-03-04  48.68
2026-03-05  52.67
2026-03-06  64.64
2026-03-07  93.98
2026-03-08  94.83
2026-03-09  58.32
2026-03-10  56.46

In [12]:
# df에서 인덱스가 '2026-02-27'과 '2026-03-27'인 행을 선택하세요.(팬시 인덱싱)
df.loc[['2026-02-27', '2026-03-27'], :]

            sales
date
2026-02-27  65.28
2026-03-27  67.51

In [13]:
# df에서 인덱스가 매월 10일인 행을 선택하세요.(불리언 인덱싱)
mask = df.index.day == 10
df.loc[mask]

            sales
date
2026-01-10  80.52
2026-02-10  38.28
2026-03-10  56.46

### 연습 문제 3: 중복 시점 확인

In [14]:
# df에서 인덱스가 중복이면 True, 중복이 아니면 False인 dup_mask를 생성하세요.
dup_mask = df.index.duplicated(False)

In [15]:
# df에서 dup_maks가 True인 행을 선택하고, dup_rows에 할당하세요.
dup_rows = df.loc[dup_mask]

In [16]:
# dup_rows를 확인하세요.
dup_rows

             sales
date
2026-01-09   53.12
2026-01-09   51.21
2026-02-12   50.35
2026-02-12   45.70
2026-03-21   98.99
2026-03-21  101.31

In [17]:
# df에서 인덱스로 그룹을 설정하고, sales의 마지막 원소를 선택하여 df에 재할당하세요.
df = pd.DataFrame(df.groupby(df.index)['sales'].last())

### 연습 문제 4: 누락 시점 확인

In [18]:
# df의 인덱스 최솟값과 최댓값으로 일별 기대 인덱스를 생성하고 full_idx에 할당하세요.
full_idx = pd.date_range(df.index.min(), df.index.max())

In [19]:
# full_idx와 비교하여 df의 인덱스에서 누락된 인덱스를 생성하고 miss_idx에 할당하세요.
miss_idx = full_idx.difference(df.index)

In [20]:
# miss_idx를 확인하세요.
miss_idx

DatetimeIndex(['2026-01-14', '2026-02-14', '2026-03-14'], dtype='datetime64[ns]', freq=None)

In [21]:
# df에서 누락된 인덱스를 추가하세요.
df = df.reindex(index=full_idx)

### 연습 문제 5: 결측값 처리

In [22]:
# df에서 sales가 결측인 행을 확인하세요.
# [참고] df에서 sales가 결측인 행은 모두 10행입니다.
mask = df['sales'].isna()
df.loc[mask]

            sales
2026-01-14    NaN
2026-01-19    NaN
2026-01-22    NaN
2026-02-14    NaN
2026-02-28    NaN
2026-03-11    NaN
2026-03-14    NaN
2026-03-16    NaN
2026-03-17    NaN
2026-03-25    NaN

In [23]:
# df에서 sales의 결측값을 선형보간법으로 채우고, sales에 재할당하세요.
df['sales'] = df['sales'].interpolate(method='linear')

In [28]:
# df에서 sales의 평균을 확인하세요.
# [참고] 실행 결과를 반올림하여 소수점 둘째자리까지 남기면 59.40이어야 합니다.
print(f'{df['sales'].mean().round(2):.2f}')

59.40

### 연습 문제 6: 시차 변수 생성

In [29]:
# df에서 sales를 1칸 아래로 이동시키고 df에 lag_1을 추가하세요.
df['lag_1'] = df['sales'].shift(1)

In [30]:
# df에서 sales를 3칸 아래로 이동시키고 df에 lag_3을 추가하세요.
df['lag_3'] = df['sales'].shift(3)

In [31]:
# df에서 sales를 7칸 아래로 이동시키고 df에 lag_7을 추가하세요.
df['lag_7'] = df['sales'].shift(7)

In [33]:
# df의 상관계수 행렬을 확인하세요.
# [참고] 실행 결과를 반올림하여 소수점 둘째자리까지 남기면 sales와 lag_7의 상관계수는 0.88이어야 합니다.
df.corr().round(2)

       sales  lag_1  lag_3  lag_7
sales   1.00   0.48  -0.44   0.88
lag_1   0.48   1.00  -0.14   0.48
lag_3  -0.44  -0.14   1.00  -0.42
lag_7   0.88   0.48  -0.42   1.00

In [35]:
# df에서 sales만 남기고 df에 재할당합니다.
df = df.filter(like='sales')

### 연습 문제 7: 이동 평균 계산

In [40]:
# df에서 sales의 7일 이동 평균을 확인하세요.
# [참고] 최소 구간을 3으로 설정하세요.
df['sales'].rolling(window=7, min_periods=3).mean().head(10)

2026-01-01          NaN
2026-01-02          NaN
2026-01-03    56.886667
2026-01-04    60.077500
2026-01-05    56.240000
2026-01-06    50.178333
2026-01-07    49.045714
2026-01-08    47.567143
2026-01-09    48.457143
2026-01-10    48.880000
Freq: D, Name: sales, dtype: float64

In [45]:
# df에서 sales의 처음부터 누적된 평균을 계산합니다.
# [참고] 실행 결과, 마지막 원소의 인덱스는 2026-03-31, 값은 59.404889이어야 합니다.
df.expanding().mean().tail(1)

                sales
2026-03-31  59.404889

### 연습 문제 8: 변화량 기반 변수 생성

In [46]:
# df에서 sales의 전일 대비 차분을 계산하세요.
# [참고] 실행 결과, 첫 번째 원소는 NaN이고 두 번째 원소는 -3.14이어야 합니다.
df['sales'].diff(1).head()

2026-01-01      NaN
2026-01-02    -3.14
2026-01-03    32.58
2026-01-04    -7.91
2026-01-05   -28.76
Freq: D, Name: sales, dtype: float64

In [47]:
# df에서 sales의 전일 대비 증감률을 계산하세요.
# [참고] 실행 결과, 첫 번째 원소는 NaN이고 두 번째 원소는 -0.065254이어야 합니다.
df.pct_change(1).head()

               sales
2026-01-01       NaN
2026-01-02 -0.065254
2026-01-03  0.724322
2026-01-04 -0.101986
2026-01-05 -0.412922

### 연습 문제 9: 시간 단위 재구성

In [51]:
# df에서 토요일이 끝나는 주간 구간으로 sales의 평균을 계산하세요.
# [참고] 실행 결과, 첫 번째 원소의 인덱스는 2026-01-03, 값은 56.886667이어야 합니다.
df.resample(rule='W-SAT')['sales'].mean().head()

2026-01-03    56.886667
2026-01-10    48.880000
2026-01-17    51.446429
2026-01-24    55.270000
2026-01-31    53.731429
Freq: W-SAT, Name: sales, dtype: float64

In [54]:
# df에서 토요일이 끝나는 주간 구간으로 sales의 평균을 계산하고, 전주 대비 증감률을 확인하세요.
# [참고] 실행 결과, 마지막 원소의 인덱스는 2026-04-04, 값은 0.027981이어야 합니다.
df.resample(rule='W-SAT')['sales'].mean().pct_change(1).tail(1)

2026-04-04    0.027981
Freq: W-SAT, Name: sales, dtype: float64

In [55]:
# df에서 sales의 인덱스가 매주 월요일인 행을 선택하고, 전체 평균을 계산하세요.
# [참고] 실행 결과, 값은 48.802564이어야 합니다.
df.asfreq(freq='W-MON').mean()

sales    48.802564
dtype: float64

## End of Document